### ISSUE TITLE
display: flex missing

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipython_widgets#19]
It seems that a fluke in the less means that generated CSS is:

```css
.hbox,.vbox,.widget-area,.widget-area .widget-subarea,.widget-hbox,.widget-hslider,.widget-radio-box,.widget-vbox,.widget-vslider,.widget-vslider .ui-slider {
    display: -webkit-box
}
```
and the display for the widget-subarea is set to `-webkit-box`, rather than `flex`.
